@echo off
echo Removing directory...
rmdir build /s /q
echo Creating directory...
mkdir build
echo Re-adding .gitkeep...
echo.>build/.gitkeep
echo Changing directory...
cd build
echo Starting CMake...
cmake ../
echo Starting MSBuild...
msbuild ALL_BUILD.vcxproj /P:Configuration=Release
echo Copying keys.json...
copy keys.json Release /Y
echo Successfully performed commands.
pause